version = 0.1
[default.deploy.parameters]
stack_name = "application-dynamo"
resolve_s3 = true
s3_prefix = "application-dynamo"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "MultimediaDBTableName=\"multimedia-datastore\""

