AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Dynamo Table for Application

Parameters:
  MultimediaDBTableName:
    Type: String
    Description: Name of the bucket

Resources:
  DBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        -
          AttributeName: "objectName"
          AttributeType: "S"
        -
          AttributeName: "objectTimestamp"
          AttributeType: "S"
        -
          AttributeName: "userName"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "userName"
          KeyType: "HASH"
        -
          AttributeName: "objectName"
          KeyType: "RANGE"
      TableName: !Ref MultimediaDBTableName
      LocalSecondaryIndexes:
        -
          IndexName: "TimeStampLSI"
          KeySchema:
            -
              AttributeName: "userName"
              KeyType: "HASH"
            -
              AttributeName: "objectTimestamp"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
