version = 0.1
[default.deploy.parameters]
stack_name = "application-image-repository"
resolve_s3 = true
s3_prefix = "application-image-repository"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "RepoName=\"application-image\""

