version = 0.1
[default.deploy.parameters]
stack_name = "gallery-application-service"
resolve_s3 = true
s3_prefix = "gallery-application-service"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
parameter_overrides = "ClusterName=\"application-cluster\" AppName=\"projit-test-service\" IngressPort=5000 ContainerName=\"aws-gallery-Container\" ALBStackName=\"Application-Public\" VPCID=\"vpc-0acbeb1e2e182ff4e\" Subnets=\"subnet-0246deaab5ced44ab,subnet-067ab74c61c0d3ea7,subnet-016abd581fe987f8e,subnet-0b61a9ece5a29ccf8,subnet-01a7d396adc2bf788,subnet-08d586b6b45833c6c\" ServicePathPattern=\"/app/*\" TaskDefinationName=\"aws-gallery-TD\" TaskDefinationRevision=\"3\" Priority=1 HealthCheckPath=\"/healthCheck\" HttpCodes=\"200-499\""