version = 0.1
[default.deploy.parameters]
stack_name = "application-user-pool"
resolve_s3 = true
s3_prefix = "application-user-pool"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "PoolName=\"gallery-pool\" ClientName=\"gallery-pool-client\""

