AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Fargate based ECS Task Definition to deploy applications in a single container

Parameters:
  AppName:
    Type: String
    Description: Name for Container and Task Family

  ContainerImageURL:
    Type: String
    Description: Container Image URL

  ContainerCPU:
    Type: Number
    Description: Container CPU Size
    AllowedValues:
      - 512
      - 1024
      - 2048
      - 3076
      - 4096

  ContainerMemory:
    Type: Number
    Description: Container Memory Size
    AllowedValues:
      - 512
      - 1024
      - 2048
      - 3076
      - 4096

  Port:
    Type: Number
    Description: Host Port Mapping
    Default: 80

  PortName:
    Type: String
    Description: Name of Port Mapping

  Region:
    Type: String
    Description: Region for AWS logs

  ReadonlyRootFilesystem:
    Type: String
    Description: Set read only access for root folder system
    AllowedValues:
      - true
      - false

  TaskCPU:
    Type: String
    Description: Amount of CPU needed for the task

  TaskMemory:
    Type: String
    Description: Amount of memory needed for the task
    AllowedValues:
      - 0.5
      - 1
      - 2
      - 4
      - 6
      - 8
      - 16

  ECSLogRetentionDays:
    Type: Number
    Description: ECS Task Log Retention Days
    Default: 7
    AllowedValues:
      - 1
      - 3
      - 5
      - 7
      - 14
      - 30
      - 60

Resources:
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      RoleName: !Sub ${AppName}-ECS-TaskExecutionRole
      Policies:
        - PolicyName: LogAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  CloudwatchLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Sub '/ecs/${AppName}-TD'
      RetentionInDays: !Ref ECSLogRetentionDays

  ApplicationTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    DependsOn: CloudwatchLogGroup
    DeletionPolicy: Retain
    Properties:
      ContainerDefinitions:
        - Name: !Sub ${AppName}-Container
          Image: !Ref ContainerImageURL
          Cpu: !Ref ContainerCPU
          Memory: !Ref ContainerMemory
          MemoryReservation: !Ref ContainerMemory
          Essential: true
          PortMappings:
            - ContainerPort: !Ref Port
              HostPort: !Ref Port
              Protocol: tcp
              AppProtocol: http
              Name: !Ref PortName
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref CloudwatchLogGroup
              awslogs-region: !Ref Region
              awslogs-stream-prefix: !Sub ${AppName}
          ReadonlyRootFilesystem: !Ref ReadonlyRootFilesystem
      Family: !Sub ${AppName}-TD
      Cpu: !Sub ${TaskCPU} vCPU
      Memory: !Sub ${TaskMemory} GB
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      RuntimePlatform:
        CpuArchitecture: X86_64
        OperatingSystemFamily: LINUX
      TaskRoleArn: !Ref AWS::NoValue



Outputs:
  ECSTaskDefinition:
    Description: The created Task Definition.
    Value: !Ref ApplicationTaskDefinition