version = 0.1
[default.deploy.parameters]
stack_name = "multimedia-preprocessor-lambda"
resolve_s3 = true
s3_prefix = "multimedia-preprocessor-lambda"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "S3BucketName=\"gallery-bucket\" DynamoTableName=\"multimedia-datastore\" LayerArns=\"arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p312-Pillow:6\""

