version = 0.1
[default.deploy.parameters]
stack_name = "application-bucket-cloudfront"
resolve_s3 = true
s3_prefix = "application-bucket-cloudfront"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "BucketName=\"album-bucket\" DeploymentName=\"album-bucket-deployment\""

