AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Template for all VPC endpopints

Parameters:
  VpcId:
    Type: String
    Description: Id of VPC

  Subnets:
    Type: String
    Description: List of Subnets

  VPCEndpointSecurityGroup:
    Type: String
    Description: VPC Endpoint Security Group



Resources:
  CWLogsEndpoint:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
        VpcEndpointType: "Interface"
        VpcId: !Ref VpcId
        ServiceName: !Sub "com.amazonaws.${AWS::Region}.logs"
        PolicyDocument: |
            {
              "Statement": [
                {
                  "Action": "*", 
                  "Effect": "Allow", 
                  "Principal": "*", 
                  "Resource": "*"
                }
              ]
            }
        SubnetIds:
          - !Split [ ",", !Ref Subnets]
        PrivateDnsEnabled: true
        SecurityGroupIds:
          - !Ref VPCEndpointSecurityGroup

    CWEndpoint:
      Type: "AWS::EC2::VPCEndpoint"
      Properties:
        VpcEndpointType: "Interface"
        VpcId: !Ref VpcId
        ServiceName: !Sub "com.amazonaws.${AWS::Region}.logs"
        PolicyDocument: |
          {
            "Statement": [
              {
                "Action": "*", 
                "Effect": "Allow", 
                "Principal": "*", 
                "Resource": "*"
              }
            ]
          }
        SubnetIds:
          - !Split [ ",", !Ref Subnets ]
        PrivateDnsEnabled: true
        SecurityGroupIds:
          - !Ref VPCEndpointSecurityGroup

