version = 0.1
[default.deploy.parameters]
stack_name = "api-registry-lambda-layer"
resolve_s3 = true
s3_prefix = "api-registry-lambda-layer"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Architectures=\"arm64,x86_64\" Runtimes=\"python3.10,python3.11,python3.12,python3.12\" S3BucketLocation=\"aws-sam-cli-managed-default-samclisourcebucket-zkhbofflf4v1\" S3KeyPath=\"layer/ApiRegistry.zip\" LayerName=\"ApiRegistry\" LayerVersion=\"1.0.1\""

