version = 0.1
[default.deploy.parameters]
stack_name = "application-ALB"
resolve_s3 = true
s3_prefix = "application-ALB"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "StackName=\"Application\" VPCID=\"\" Subnets=\"\" RequestTimeOut=\"60\""

