version = 0.1
[default.deploy.parameters]
stack_name = "application-ALB"
resolve_s3 = true
s3_prefix = "application-ALB"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "StackName=\"Application\" VPCID=\"vpc-0ba8dc166b641aa2b\" Subnets=\"subnet-05827c47b9a6e2a13,subnet-0dd2c88b406bab802,subnet-0903609d518d0e524,subnet-07b372d00b58284c5,subnet-004ae6f38caf005ef,subnet-07fb8af33aafd34ae\" RequestTimeOut=\"60\""

