version = 0.1
[default.deploy.parameters]
stack_name = "application-cert"
resolve_s3 = true
s3_prefix = "application-cert"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "DomainName=\"apps.proapplication.net\" HostedZoneId=\"Z0716017FNQSL38BA6TG\""

